_welcome:
    path:  /
    defaults: { _controller: FishtrapJsongamesBundle:Welcome:index }

_problem_start:
    path:  /problem/{problemSlug}
    defaults: { _controller: FishtrapJsongamesBundle:Problem:start }

_problem_finish:
    path:  /problem/{problemSlug}/hash/{hash}/answer
    defaults: { _controller: FishtrapJsongamesBundle:Problem:submit }